#!/usr/bin/env python3
"""Master manifest of NEW candidate pairs for Tashkent album expansion.
Existing 20 pairs are EXCLUDED (amir_temur 1910s, eski shahar 1900s, sirk birinchi,
navoiy teatr, mustaqillik x2, zoopark, sirk 1980s, vokzal 1980s, chorsu interior,
tramvay, mehmonxona O'zbekiston, san'at muzeyi, xalqlar dostligi, metro kosmonavtlar,
sayilgoh, zilzila/jasorat, romanov, aeroport, chilonzor).
Fields: id, title_uz (page title), chapter (1|2|3), lat, lng, old_q, new_q, cached
"""

CANDIDATES = [
    # ============ CHAPTER I — Qadimgi Toshkent (1900–1930) ============
    dict(id="kukeldash",      title_uz="Kukeldash madrasasi",                       ch=1, lat=41.3246, lng=69.2299,
         old_q="Кукельдаш медресе Ташкент старая фотография начало 20 века",
         new_q="Кукельдаш медресе Ташкент сегодня фото", cached=True),
    dict(id="juma_masjid",    title_uz="Juma masjidi (Xo‘ja Ahror valoyati)",        ch=1, lat=41.3229, lng=69.2246,
         old_q="мечеть Джами Ташкент старая фотография 1900-е",
         new_q="мечеть Джами Ташкент сегодня фото", cached=False),
    dict(id="hazratimom",     title_uz="Hazrati Imom majmuasi (Barakxon madrasasi)", ch=1, lat=41.3350, lng=69.2281,
         old_q="медресе Баракхан Ташкент старая фотография",
         new_q="Хазрати Имам комплекс Ташкент сегодня", cached=True),
    dict(id="qaffol",         title_uz="Qaffol Shoshiy maqbarasi",                   ch=1, lat=41.3341, lng=69.2287,
         old_q="мавзолей Каффаля Шаши Ташкент старое фото",
         new_q="мавзолей Каффаля Шаши Ташкент сегодня", cached=False),
    dict(id="shayxontohur",   title_uz="Shayxontohur majmuasi",                      ch=1, lat=41.3307, lng=69.2269,
         old_q="мавзолей Шейхантаур Ташкент старая фотография",
         new_q="мавзолей Шейхантаур Ташкент сегодня", cached=False),
    dict(id="yunusxon",       title_uz="Yunusxon maqbarasi",                         ch=1, lat=41.3340, lng=69.2185,
         old_q="мавзолей Юнусхана Ташкент старое фото",
         new_q="мавзолей Юнусхана Ташкент сегодня", cached=False),
    dict(id="abdulkosim",     title_uz="Abdulkosim madrasasi (Oqtepa)",              ch=1, lat=41.3053, lng=69.2526,
         old_q="медресе Абдулкасыма Ташкент старая фотография",
         new_q="медресе Абдулкасыма Ташкент сегодня", cached=False),
    dict(id="hadra",          title_uz="Xadra maydoni",                              ch=1, lat=41.3265, lng=69.2309,
         old_q="площадь Хадра Ташкент старое фото",
         new_q="площадь Хадра Ташкент сегодня", cached=False),
    dict(id="cherch",         title_uz="Muqaddas Yurak cherkovi (katolik kostyoli)", ch=1, lat=41.3110, lng=69.2688,
         old_q="костёл Ташкент Сердце Иисуса старая фотография",
         new_q="костёл Сердце Иисуса Ташкент сегодня", cached=False),
    dict(id="polovsev",       title_uz="Amaliy san’at muzeyi (sobiq dacha)",         ch=1, lat=41.3120, lng=69.2748,
         old_q="Музей прикладного искусства Ташкент старое фото",
         new_q="Музей прикладного искусства Ташкент сегодня", cached=False),
    dict(id="vokzal_eski",    title_uz="Toshkent vokzali — birinchi bino",           ch=1, lat=41.3210, lng=69.2328,
         old_q="Ташкентский вокзал 1900-е старая фотография",
         new_q="Ташкентский железнодорожный вокзал здание", cached=False),
    dict(id="sinagoga",       title_uz="Toshkent sinagogasi",                        ch=1, lat=41.3130, lng=69.2620,
         old_q="Ташкентская синагога старая фотография",
         new_q="Ташкентская синагога сегодня", cached=False),
    dict(id="passage",        title_uz="Aleksandr pasaji",                           ch=1, lat=41.3149, lng=69.2871,
         old_q="Александровский пассаж Ташкент старая фотография",
         new_q="Александровский пассаж Ташкент сегодня", cached=False),
    dict(id="uspenskiy",      title_uz="Uspenskiy kafedral sobori",                  ch=1, lat=41.3560, lng=69.2680,
         old_q="Успенский кафедральный собор Ташкент старое фото",
         new_q="Успенский кафедральный собор Ташкент сегодня", cached=False),
    dict(id="kaldirgoch",     title_uz="Kaldirgo‘chbiy maqbarasi",                   ch=1, lat=41.3270, lng=69.2170,
         old_q="мавзолей Калдыргач-бия Ташкент",
         new_q="мавзолей Калдыргач-бия Ташкент сегодня", cached=False),

    # ============ CHAPTER II — Yangi davr bo‘sag‘asi (1930–1960) ============
    dict(id="milliy_teatr",   title_uz="O‘zbek Milliy akademik drama teatri",        ch=2, lat=41.3216, lng=69.2713,
         old_q="драматический театр Хамзы Ташкент старая фотография",
         new_q="Национальный академический драматический театр Ташкент сегодня", cached=False),
    dict(id="muqimiy_teatr",  title_uz="Muqimiy nomidagi musiqali drama teatri",     ch=2, lat=41.3242, lng=69.2700,
         old_q="театр Мукими Ташкент старая фотография",
         new_q="театр Мукими Ташкент сегодня", cached=False),
    dict(id="kutubxona",      title_uz="Alisher Navoiy nomidagi kutubxona",          ch=2, lat=41.3147, lng=69.2880,
         old_q="Государственная публичная библиотека Ташкент старое фото",
         new_q="Национальная библиотека Узбекистана имени Навои Ташкент", cached=False),
    dict(id="konservatoriya", title_uz="Toshkent konservatoriyasi",                  ch=2, lat=41.3176, lng=69.2834,
         old_q="Ташкентская консерватория старая фотография",
         new_q="Государственная консерватория Узбекистана Ташкент сегодня", cached=False),
    dict(id="sabir",          title_uz="Mukimiy? — Sabir yodgorligi",                ch=2, lat=41.3170, lng=69.2800,
         old_q="памятник Сабиру Ташкент старая фотография",
         new_q="памятник Сабиру Ташкент сегодня", cached=False),
    dict(id="nizomiy",        title_uz="Nizomiy Ganjaviy yodgorligi",                ch=2, lat=41.3159, lng=69.2771,
         old_q="памятник Низами Ташкент старая фотография",
         new_q="памятник Низами Ташкент сегодня", cached=False),
    dict(id="pushkin",        title_uz="Pushkin yodgorligi",                         ch=2, lat=41.3220, lng=69.2790,
         old_q="памятник Пушкину Ташкент старая фотография",
         new_q="памятник Пушкину Ташкент сегодня", cached=False),
    dict(id="anhor",          title_uz="Anhor kanali va ko‘prigi",                   ch=2, lat=41.3125, lng=69.2795,
         old_q="канал Анхор Ташкент старая фотография набережная",
         new_q="канал Анхор Ташкент сегодня набережная", cached=True),
    dict(id="dinamo",         title_uz="«Dinamo» stadioni",                          ch=2, lat=41.3123, lng=69.2557,
         old_q="стадион Динамо Ташкент старая фотография",
         new_q="стадион Динамо Ташкент сегодня", cached=False),
    dict(id="toqimachilik",   title_uz="Toshkent to‘qimachilik kombinati",           ch=2, lat=41.2940, lng=69.2260,
         old_q="Ташкентский текстильный комбинат старая фотография",
         new_q="Ташкентский текстильный комбинат сегодня", cached=False),

    # ============ CHAPTER III — Buyuk qurilish davri (1960–2000) ============
    dict(id="amirtemur_1970", title_uz="Amir Temur xiyoboni (sobiq Karl Marks maydoni)", ch=3, lat=41.3113, lng=69.2811,
         old_q="площадь Карла Маркса Ташкент старое фото 1970-е",
         new_q="площадь Амира Темура Ташкент памятник сегодня", cached=False),
    dict(id="tarix_muzeyi",   title_uz="O‘zbekiston tarixi davlat muzeyi",           ch=3, lat=41.3144, lng=69.2601,
         old_q="музей Ленина Ташкент старая фотография здание",
         new_q="музей истории Узбекистана Ташкент здание сегодня", cached=False),
    dict(id="teleminora",     title_uz="Toshkent teleminorasi",                      ch=3, lat=41.3290, lng=69.2912,
         old_q="Ташкентская телевизионная башня 1980-е старое фото",
         new_q="Ташкентская телевизионная башня сегодня", cached=False),
    dict(id="metro_amirtimur", title_uz="«Amir Temur xiyoboni» metro bekat",         ch=3, lat=41.3103, lng=69.2807,
         old_q="метро площадь Пушкина Ташкент 1977 старое фото станция",
         new_q="метро станция Амира Темура хиёбони Ташкент зал", cached=False),
    dict(id="paxtakor_stadion", title_uz="«Paxtakor» markaziy stadioni",             ch=3, lat=41.3128, lng=69.2590,
         old_q="стадион Пахтакор Ташкент старая фотография",
         new_q="стадион Пахтакор Ташкент сегодня", cached=False),
    dict(id="bobur_maydoni",  title_uz="Bobur maydoni (sobiq Gorkiy bog‘i)",         ch=3, lat=41.3228, lng=69.2752,
         old_q="парк Горького Ташкент старая фотография",
         new_q="площадь Бабура Ташкент сегодня", cached=False),
    dict(id="panfilov",       title_uz="Panfilov bog‘i va ko‘ngilochar markazi",     ch=3, lat=41.3067, lng=69.2849,
         old_q="парк Панфилова Ташкент старое фото колесо обозрения",
         new_q="парк Панфилова Ташкент сегодня колесо обозрения", cached=False),
    dict(id="dengiz",         title_uz="Toshkent dengizi",                           ch=3, lat=41.3508, lng=69.3059,
         old_q="Ташкентское море пляж старая фотография 1970-е",
         new_q="Ташкентское море сегодня пляж", cached=False),
    dict(id="shevchenko",     title_uz="Taras Shevchenko yodgorligi",                ch=3, lat=41.3178, lng=69.2952,
         old_q="памятник Шевченко Ташкент старая фотография",
         new_q="памятник Шевченко Ташкент сегодня", cached=False),
    dict(id="planetariy",     title_uz="Toshkent planetariysi",                      ch=3, lat=41.3174, lng=69.2903,
         old_q="планетарий Ташкент старая фотография",
         new_q="планетарий Ташкент сегодня", cached=False),
    dict(id="toshkent_kino",  title_uz="«Toshkent» kinoteatri",                      ch=3, lat=41.3200, lng=69.2870,
         old_q="кинотеатр Ташкент старая фотография здание",
         new_q="кинотеатр Ташкент сегодня здание", cached=False),
    dict(id="yosh_teatr",     title_uz="Yosh tomoshabinlar teatri",                  ch=3, lat=41.3207, lng=69.2748,
         old_q="ТЮЗ Ташкент театр юного зрителя старое фото",
         new_q="Молодёжный театр Узбекистана Ташкент сегодня", cached=False),
    dict(id="toshkent_mehmonxona", title_uz="«Toshkent» mehmonxonasi",               ch=3, lat=41.3104, lng=69.2804,
         old_q="гостиница Ташкент 1960-е старая фотография",
         new_q="гостиница Ташкент сегодня здание", cached=False),
    dict(id="tsum",           title_uz="Markaziy universal do‘kon (TsUM)",           ch=3, lat=41.3134, lng=69.2830,
         old_q="ЦУМ Ташкент старая фотография",
         new_q="ЦУМ Ташкент сегодня", cached=False),
    dict(id="humo",           title_uz="Aviasozlar saroyi — «Humo Arena»",           ch=3, lat=41.3010, lng=69.3140,
         old_q="дворец культуры авиационного завода Ташкент старое фото",
         new_q="Humo Arena Ташкент ледовый дворец", cached=False),
    dict(id="qoyliq",         title_uz="Qo‘yliq bozori",                             ch=3, lat=41.2900, lng=69.2320,
         old_q="Куйлюкский рынок Ташкент старое фото",
         new_q="рынок Куйлюк Ташкент сегодня", cached=False),
    dict(id="yunusobod",      title_uz="Yunusobod massivi",                          ch=3, lat=41.3650, lng=69.3000,
         old_q="Юнусабадский массив Ташкент 1980-е старое фото",
         new_q="Юнусабадский район Ташкент сегодня", cached=False),
    dict(id="hukumat",        title_uz="O‘zbekiston hukumat saroyi",                 ch=3, lat=41.3130, lng=69.2600,
         old_q="дом Советов Ташкент старая фотография здание",
         new_q="кабинет министров Узбекистана Ташкент здание", cached=False),
    dict(id="ulugbek_yodgorlik", title_uz="Mirzo Ulug‘bek yodgorligi",               ch=3, lat=41.3440, lng=69.2880,
         old_q="памятник Улугбеку Ташкент старая фотография",
         new_q="памятник Улугбеку Ташкент сегодня", cached=False),
    dict(id="navoiy_yodgorlik", title_uz="Alisher Navoiy yodgorligi",                ch=3, lat=41.3165, lng=69.2797,
         old_q="памятник Навои Ташкент 1970-е старая фотография",
         new_q="памятник Навои Ташкент сегодня", cached=False),
    dict(id="trolleybus",     title_uz="Toshkent trolleybusi (tarixiy qatnov)",      ch=3, lat=41.3280, lng=69.2620,
         old_q="троллейбус Ташкент старая фотография 1980-е",
         new_q="улица Амира Темура Ташкент сегодня транспорт", cached=False),
    dict(id="rodina_kino",    title_uz="«Rodina» kinoteatri binosi",                 ch=3, lat=41.3146, lng=69.2871,
         old_q="кинотеатр Родина Ташкент старая фотография",
         new_q="кинотеатр Узбекистан Ташкент здание сегодня", cached=False),
    dict(id="filarmoniya",    title_uz="Davlat filarmoniyasi",                       ch=3, lat=41.3129, lng=69.2797,
         old_q="Ташкентская филармония старая фотография",
         new_q="Государственная филармония Узбекистана Ташкент сегодня", cached=False),
    dict(id="toshtech",       title_uz="Toshkent texnika universiteti (ToshTech)",   ch=3, lat=41.3330, lng=69.3200,
         old_q="Ташкентский политехнический институт старая фотография главное здание",
         new_q="Ташкентский государственный технический университет главное здание", cached=False),
    dict(id="dtu",            title_uz="Mirzo Ulug‘bek nomidagi milliy universitet", ch=3, lat=41.3370, lng=69.3057,
         old_q="Ташкентский государственный университет старое фото главное здание",
         new_q="Национальный университет Узбекистана Ташкент главное здание", cached=False),
    dict(id="chorsu_gumbaz",  title_uz="Chorsu bozori gumbazi (tashqaridan)",        ch=3, lat=41.3262, lng=69.2369,
         old_q="Чорсу купол Ташкент старая фотография площадь",
         new_q="Чорсу базар купол Ташкент снаружи сегодня", cached=False),
    dict(id="ippirodrom",     title_uz="Toshkent ippodromi",                         ch=3, lat=41.3570, lng=69.2780,
         old_q="Ташкентский ипподром старая фотография",
         new_q="Ташкентский ипподром сегодня", cached=False),
    dict(id="tit",            title_uz="Temir yo‘l muhandislari instituti",          ch=3, lat=41.3380, lng=69.2600,
         old_q="институт инженеров железнодорожного транспорта Ташкент старое фото",
         new_q="Ташкентский институт инженеров железнодорожного транспорта сегодня", cached=False),
]

if __name__ == "__main__":
    import collections
    c = collections.Counter(x["ch"] for x in CANDIDATES)
    cached = sum(1 for x in CANDIDATES if x["cached"])
    print(f"Total candidates: {len(CANDIDATES)} | ch1={c[1]} ch2={c[2]} ch3={c[3]} | cached searches: {cached}")
